name: Build image and push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-demo-image:${{ github.sha }}

    - name: Tag image with Registry
      run: docker tag my-demo-image:${{ github.sha }} my-registry/my-demo-image:${{ github.sha }}
      
# Begin of Aqua Scan
    - name: Login to Aqua Registry
      run: docker login registry.aquasec.com -u ${{ secrets.AQUA_REGISTRY_USER }} -p ${{ secrets.AQUA_REGISTRY_PASSWORD }}

    - name: Pull Aqua Scanner
      run: docker pull registry.aquasec.com/scanner:latest-saas

    - name: Run Aqua Image Scan
      run: docker run -e BUILD_JOB_NAME=$GITHUB_REPOSITORY -e BUILD_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID -e BUILD_NUMBER=$GITHUB_RUN_ID  --rm -v /var/run/docker.sock:/var/run/docker.sock registry.aquasec.com/scanner:latest-saas scan -H ${{ secrets.AQUA_CONSOLE_URL }} --token ${{ secrets.AQUA_SCANNER_TOKEN }} --local my-demo-image:${{ github.sha }} --registry "ehardisty-dockerhub"
# End of Aqua Scan 

    - name: Push to Registry
      run: echo "docker push my-registry/my-demo-image:${{ github.sha }}"
